### ISSUE TITLE
got error "Incorrect padding"

### ISSUE THREAD

**Issue by craynic** [cloudify-incubator/cloudify-kubernetes-plugin#66]
I'm getting this error when I try to make one deployment with a blueprint from `wordpress-blueprint.yaml` in this repo. I've put the three files (ca.crt, client.crt, client.key) in secrets. They are created by minikube and kubectl can use them with no problem. Now I keep getting this error. Am I missing anything?

    Traceback (most recent call last):
      File "/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 625, in main
        payload = handler.handle()
      File "/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 390, in handle
        result = self.func(*self.args, **kwargs)
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/decorators.py", line 115, in wrapper
        authentication_property
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/k8s/client.py", line 61, in __init__
        self.api = api_configuration.prepare_api()
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/k8s/config.py", line 35, in prepare_api
        api = self._do_prepare_api()
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/k8s/config.py", line 163, in _do_prepare_api
        **self.kwargs
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/k8s/config.py", line 35, in prepare_api
        api = self._do_prepare_api()
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/cloudify_kubernetes/k8s/config.py", line 114, in _do_prepare_api
        loader.load_and_set(config)
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 253, in load_and_set
        self._load_cluster_info()
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 232, in _load_cluster_info
        file_base_path=self._config_base_path).as_file()
      File "/env/plugins/default_tenant/cloudify-kubernetes-plugin-2.0.0/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 97, in as_file
        base64.decodestring(self._data.encode()))
      File "/usr/lib64/python2.7/base64.py", line 321, in decodestring
        return binascii.a2b_base64(s)
    Error: Incorrect padding

I also tried using pure base64 encoded string. No error reported in this step, but SSL verification failed when connecting to kubernetes.

**Comment by EarthmanT** [comment]
@craynic You are not responsible for base64 encoding your credentials in the kube config.

There are two solutions that immediately come to mind if you are certain that your credentials are valid:

1) How did you create the secrets in your manager? We see a lot of users running into problems with storing multi-line strings, keys, etc in secrets. The recommended method is to use the CLI in conjunction with the `-f` and a file path. Store the key in a file and execute `cfy secrets create my_secret -f /path/to/key`.

2) The wordpress-blueprint.yaml inputs, the configuration dictionary uses keys that expect strings, not file paths [here](https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/blob/master/examples/wordpress-blueprint.yaml#L39), [here](https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/blob/master/examples/wordpress-blueprint.yaml#L49), and [here](https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/blob/master/examples/wordpress-blueprint.yaml#L50). These key names will need to be changed to certificate-authority, client-certificate, and client-key respectively.

**Comment by craynic** [comment]
with Cloudify 4.0.1, localkube 1.9.0, minikube 0.25.0

**Comment by craynic** [comment]
1. I created the secrets with arg `-f`. I've checked it with the restful api.
2. I'm using the default inputs. I only give the secrets.

**Comment by EarthmanT** [comment]
You can override the default input `kubernetes_master_configuration` with the complete configuration as you use it in kube config. I would test this next.

**Comment by craynic** [comment]
I also tried overriding the default input, something like this:

    inputs:
    
      kubernetes_certificate_authority_data:
        default: |
          -----BEGIN CERTIFICATE-----
          MIIC5zCCAc+gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
          xxxxxxxx

Got the same error.

**Comment by EarthmanT** [comment]
I intended specifically the `kubernetes_master_configuration ` input, but you can also directly place the config in the master node property as [described in the plugin docs](https://docs.cloudify.co/4.2.0/plugins/kubernetes/#authentication).

By the way, yesterday I saw this error from another user (using a different blueprint), and the cause was that this relationship was missing from their blueprint:

```yaml
    relationships:
      - type: cloudify.kubernetes.relationships.managed_by_master
        target: kubernetes_master
```

**Comment by craynic** [comment]
Tried overriding the default for `kubernetes_master_configuration`, the same error raised.
I'm also sure the relationship exists.

**Comment by craynic** [comment]
I'm using Cloudify 4.0.1, both cli and manager. Does it matter?
If I upgrade to 4.2, will it help?

**Comment by EarthmanT** [comment]
1. I see in [your example](https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/issues/66#issuecomment-365142159) the key is not base64 encoded. Did you say that you did try base64 encoding all of your certs and keys already? I was mistaken that you do not need to encode your keys. They must be encoded if they are not already encoded.
2. Do you have the ability to generate authentication tokens to your environment? We are releasing #69 in a couple days with support for token authentication method.

**Comment by craynic** [comment]
Well it works. But it seems strange to me. The key and certs have been encoded, and we encode them again. If it is really necessary, hope it to be documented.
Authentication tokens seem nice. We will consider it.
